app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app.logout:
    path: /logout
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
